default[:leiningen][:version] = "2.0.0"
default[:leiningen][:install_script] = "https://github.com/technomancy/leiningen/raw/#{leiningen[:version]}/bin/lein"
default[:leiningen][:jar_url] = "https://leiningen.s3.amazonaws.com/downloads/leiningen-#{node[:leiningen][:version]}-standalone.jar"
default[:leiningen][:jar_checksum] = "939d3ca40fb681113bcc902b147b1cfb1c48f54fcafe9954a1ac955c53985b82"
default[:leiningen][:jar_dir] = "/usr/share/java"
